#!/usr/bin/env python3
"""
Import Orders from CSV to Database

This script imports the orders data from the CSV file generated by simple_orders_downloader.py
into the SQLite database for use by the dashboard.
"""

import os
import csv
import sqlite3
import logging
from datetime import datetime, timezone
from typing import List, Dict, Any

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

DB_PATH = os.path.join(os.path.dirname(__file__), 'trades.db')

def init_orders_database():
    """Initialize the orders table in the database"""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Create orders table if it doesn't exist
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS orders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            order_id TEXT UNIQUE NOT NULL,
            client_order_id TEXT,
            symbol TEXT NOT NULL,
            side TEXT NOT NULL,
            qty REAL NOT NULL,
            filled_qty REAL,
            filled_avg_price REAL,
            status TEXT NOT NULL,
            order_type TEXT,
            order_class TEXT,
            time_in_force TEXT,
            limit_price REAL,
            stop_price REAL,
            created_at TEXT,
            submitted_at TEXT,
            filled_at TEXT,
            canceled_at TEXT,
            failed_at TEXT,
            expired_at TEXT,
            updated_at TEXT,
            extended_hours BOOLEAN,
            notional REAL,
            date_added TEXT NOT NULL,
            UNIQUE(order_id)
        )
    ''')
    
    # Create indexes for faster queries
    cursor.execute('CREATE INDEX IF NOT EXISTS idx_symbol ON orders(symbol)')
    cursor.execute('CREATE INDEX IF NOT EXISTS idx_created_at ON orders(created_at)')
    cursor.execute('CREATE INDEX IF NOT EXISTS idx_filled_at ON orders(filled_at)')
    cursor.execute('CREATE INDEX IF NOT EXISTS idx_status ON orders(status)')
    cursor.execute('CREATE INDEX IF NOT EXISTS idx_date ON orders(date(created_at))')
    
    conn.commit()
    conn.close()
    logger.info("Orders database initialized")

def import_orders_from_csv(csv_file_path: str):
    """Import orders from CSV file to database"""
    if not os.path.exists(csv_file_path):
        logger.error(f"CSV file not found: {csv_file_path}")
        return
    
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    imported_count = 0
    skipped_count = 0
    
    try:
        with open(csv_file_path, 'r', newline='', encoding='utf-8') as csvfile:
            reader = csv.DictReader(csvfile)
            
            for row in reader:
                try:
                    # Insert order
                    cursor.execute('''
                        INSERT OR IGNORE INTO orders (
                            order_id, client_order_id, symbol, side, qty, filled_qty, filled_avg_price,
                            status, order_type, order_class, time_in_force, limit_price, stop_price,
                            created_at, submitted_at, filled_at, canceled_at, failed_at, expired_at,
                            updated_at, extended_hours, notional, date_added
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ''', (
                        row.get('id', ''),
                        row.get('client_order_id', ''),
                        row.get('symbol', ''),
                        row.get('side', ''),
                        float(row.get('qty', 0)) if row.get('qty') else 0,
                        float(row.get('filled_qty', 0)) if row.get('filled_qty') else None,
                        float(row.get('filled_avg_price', 0)) if row.get('filled_avg_price') else None,
                        row.get('status', ''),
                        row.get('order_type', ''),
                        row.get('order_class', ''),
                        row.get('time_in_force', ''),
                        float(row.get('limit_price', 0)) if row.get('limit_price') else None,
                        float(row.get('stop_price', 0)) if row.get('stop_price') else None,
                        row.get('created_at', ''),
                        row.get('submitted_at', ''),
                        row.get('filled_at', ''),
                        row.get('canceled_at', ''),
                        row.get('failed_at', ''),
                        row.get('expired_at', ''),
                        row.get('updated_at', ''),
                        row.get('extended_hours', '').lower() == 'true' if row.get('extended_hours') else False,
                        float(row.get('notional', 0)) if row.get('notional') else None,
                        datetime.now(timezone.utc).isoformat()
                    ))
                    
                    if cursor.rowcount > 0:
                        imported_count += 1
                    else:
                        skipped_count += 1
                        
                except Exception as e:
                    logger.error(f"Error importing order {row.get('id', 'unknown')}: {e}")
                    continue
        
        conn.commit()
        logger.info(f"Import completed: {imported_count} new orders imported, {skipped_count} existing orders skipped")
        
    except Exception as e:
        logger.error(f"Error reading CSV file: {e}")
    finally:
        conn.close()

def get_latest_csv_file():
    """Find the most recent CSV file in the backend directory"""
    backend_dir = os.path.dirname(__file__)
    csv_files = [f for f in os.listdir(backend_dir) if f.startswith('alpaca_orders_') and f.endswith('.csv')]
    
    if not csv_files:
        return None
    
    # Sort by filename (which includes timestamp) to get the latest
    csv_files.sort(reverse=True)
    return os.path.join(backend_dir, csv_files[0])

def main():
    """Main function to import orders from CSV"""
    try:
        logger.info("Starting orders CSV import...")
        
        # Initialize database
        init_orders_database()
        
        # Find the latest CSV file
        csv_file = get_latest_csv_file()
        if not csv_file:
            logger.error("No CSV files found. Please run simple_orders_downloader.py first.")
            return
        
        logger.info(f"Found CSV file: {csv_file}")
        
        # Import orders
        import_orders_from_csv(csv_file)
        
        logger.info("Orders CSV import completed successfully")
        
    except Exception as e:
        logger.error(f"Error in main execution: {e}")
        raise

if __name__ == "__main__":
    main()
